### ISSUE TITLE
Название игры

### ISSUE THREAD

**Issue by SalemDrk** [bmstu-iu9/utp2019-7-2d-game#14]
Пора придумать финальное название игры (нужно как минимум для отрисовки главного меню)

**Comment by Vigorge** [comment]
Как насчёт пародии на Индиану Джонса в названии. Можно что-то о типу: Алабама Смит и Гробница Фараона или что-то в этом духе.
P.S. Алабама, потому что это штат, как и Индиана :)

**Comment by SalemDrk** [comment]
Идея неплохая
на русском или на английском?

**Comment by curryrasul** [comment]
John from India )))

**Comment by Vigorge** [comment]
> Идея неплохая
> на русском или на английском?

Ну, на английском солиднее)

**Comment by SalemDrk** [comment]
ага
Ahmed from Russia))))
