### ISSUE TITLE
Рефакторинг 

### ISSUE THREAD

**Issue by Vigorge** [bmstu-iu9/utp2019-7-2d-game#8]
- [x] Провести редактуру кода и привести его к стандартам правил написания
- [x] Ничего не сломать :)

**Comment by SalemDrk** [comment]
Так как еще в первом семестре нам было сказано не использовать var в JS, при рефакторинге заменяю var на let. Во всех файлах этот трюк проходит, кроме parseMap. Там при замене все ломается. Как думаете, в чем может быть проблема?
